### ISSUE TITLE
[Feature] Email Signup

### ISSUE THREAD

**Issue by Fingolf6455** [FabianVolkers/face-the-facts-app#128]
**Is your feature request related to a problem? Please describe.**
As an User I want to sign-up with my email address on the landing page to get updates on Face the Facts.

**Describe the solution you'd like**
A way to collect and store those email address in a simple backend.
Some alternatives would be great but mostly something cheap and free. 
The feature is mostly there to give us credibility.

**Additional context**

**Comment by Urhengulas** [comment]
# options

## google form
* As a website visitor I click on a button, which leads me to a public google form where I can submit my email-address (and other details?).
* As a PM I see all the gathered information in a google spreadsheet.
* As a SE I implement  button with a link to the google form.

| pro | con |
| :--- | :--- |
| easy to implement | unclear if this is okay from a data privacy perspective |
| unlimited via student suite | some people might feel uncomfortable giving their information to google |

## mailchimp
_(https://mailchimp.com/features/custom-forms/)_

* As a website visitor I see a form where I can directly fill-in my emailaddress. 
* As a PM I see all the email addresses in the mailchimp UI and can export it as csv. I also could use the other fancy mailchimp features.
* As a SE I can either copy-paste the form from mailchimp or style my own (https://mailchimp.com/help/host-your-own-signup-forms/).

| pro | con |
| :--- | :--- |
| probably better UX (user doesn't leave page) | free tier "only" up to 2000 contacts (see comaparison: https://mailchimp.com/pricing/marketing/compare-plans/) |
| easy to implement | |
| option of using other marketing features | |

# my preference
Mailchimp, because it looks more professional.

# TODO
- [ ] Create mailchimp account @Fingolf6455 
- [ ] Create form in mailchimp UI @Fingolf6455 or @RichardKruemmel 
- [ ] Implement form in website @RichardKruemmel
