### ISSUE TITLE
[Chore] Repo: Clean Up Git History

### ISSUE THREAD

**Issue by FabianVolkers** [FabianVolkers/face-the-facts-app#47]
# Clean Up History

Squash commits for each PR that happened. 

Process: Start from initial commit and cherry pick all commits into new branches off of develop-clean, squashing them on merge.

## ToDos
- [x] Cherry Pick merges
  - [x] #1 [Feature] Scan: Camera support
  - [x] #2 [CI/CD] Docker: Dockerfile for dev version
  - [x] #3
  - [x] #4 [Hotfix] VoteChart: Canvas Styling on Global Canvas Element
  - [x] #5 [Feature] ControversyCard: Add Expandability
  - [x] #6 [Feature] Profile, Votes: Horizontal Scroll
  - [x] #7 [Chore] ProfileHeader: Refactor
  - [x] #8 [Chore] SubHeading: Refactor
  - [x] #9 [CI/CD] Docker: Production ready setup
  - [x] #10 [Feature] Scan: Candidate Detection
- [x] Rebase active branches
  - [x] ElectionChances
  - [x] Header
  - [x] SecondVote
  - [x] Search
  - [x] Profile Redesign
- [x]  Rename develop -> archive/develop, develop-clean -> develop; switch default branches
- [x] Mention co-authors in squashed commits
- [x] Remove stale branches

## PRs
| PR                                                 | First Commit | Last Commit |
|----------------------------------------------------|--------------|-------------|
| [#1](https://github.com/FaceTheFacts/web/pull/1)   | 7742285      | 14f92e9     |
| [#2](https://github.com/FaceTheFacts/web/pull/2)   | 2286ec7      | 2286ec7     |
| [#3](https://github.com/FaceTheFacts/web/pull/3)   | f375f1a      | ac7e9e5     |
| [#4](https://github.com/FaceTheFacts/web/pull/4)   | 2f62b56      | d678576     |
| [#5](https://github.com/FaceTheFacts/web/pull/5)   | feeb3ea      | 4d43b0d     |
| [#6](https://github.com/FaceTheFacts/web/pull/6)   | 22c8eb7      | 197adeb     |
| [#7](https://github.com/FaceTheFacts/web/pull/7)   | b86c825      | e1a4a9d     |
| [#8](https://github.com/FaceTheFacts/web/pull/8)   | 14122cc      | 945961e     |
| [#9](https://github.com/FaceTheFacts/web/pull/9)   | 21e10b9      | 21e10b9     |
| [#10](https://github.com/FaceTheFacts/web/pull/10) | ad23ad4      | 5cce803     |
| [#11](https://github.com/FaceTheFacts/web/pull/11) |              |             |
| [#12](https://github.com/FaceTheFacts/web/pull/12) |              |             |
| [#13](https://github.com/FaceTheFacts/web/pull/13) |              |             |
| [#14](https://github.com/FaceTheFacts/web/pull/14) |              |             |
| [#15](https://github.com/FaceTheFacts/web/pull/15) |              |             |
| [#16](https://github.com/FaceTheFacts/web/pull/16) |              |             |
| [#17](https://github.com/FaceTheFacts/web/pull/17) |              |             |
| [#18](https://github.com/FaceTheFacts/web/pull/18) |              |             |
| [#19](https://github.com/FaceTheFacts/web/pull/19) |              |             |
| [#20](https://github.com/FaceTheFacts/web/pull/20) |              |             |
| [#21](https://github.com/FaceTheFacts/web/pull/21) |              |             |
| [#22](https://github.com/FaceTheFacts/web/pull/22) |              |             |
| [#23](https://github.com/FaceTheFacts/web/pull/23) |              |             |
| [#24](https://github.com/FaceTheFacts/web/pull/24) |              |             |
| [#25](https://github.com/FaceTheFacts/web/pull/25) |              |             |
| [#26](https://github.com/FaceTheFacts/web/pull/26) |              |             |
| [#27](https://github.com/FaceTheFacts/web/pull/27) |              |             |
| [#28](https://github.com/FaceTheFacts/web/pull/28) |              |             |
| [#29](https://github.com/FaceTheFacts/web/pull/29) |              |             |
| [#30](https://github.com/FaceTheFacts/web/pull/30) |              |             |
| [#31](https://github.com/FaceTheFacts/web/pull/31) |              |             |
| [#32](https://github.com/FaceTheFacts/web/pull/32) |              |             |
| [#33](https://github.com/FaceTheFacts/web/pull/33) |              |             |
| [#34](https://github.com/FaceTheFacts/web/pull/34) |              |             |
| [#35](https://github.com/FaceTheFacts/web/pull/35) |              |             |
| [#36](https://github.com/FaceTheFacts/web/pull/36) |              |             |
| [#37](https://github.com/FaceTheFacts/web/pull/37) |              |             |
| [#38](https://github.com/FaceTheFacts/web/pull/38) |              |             |
| [#39](https://github.com/FaceTheFacts/web/pull/39) |              |             |
| [#40](https://github.com/FaceTheFacts/web/pull/40) |              |             |
| [#41](https://github.com/FaceTheFacts/web/pull/41) |              |             |
| [#42](https://github.com/FaceTheFacts/web/pull/42) |              |             |
| [#43](https://github.com/FaceTheFacts/web/pull/43) |              |             |
| [#44](https://github.com/FaceTheFacts/web/pull/44) |              |             |
| [#45](https://github.com/FaceTheFacts/web/pull/45) |              |             |
| [#46](https://github.com/FaceTheFacts/web/pull/46) |              |             |
| [#47](https://github.com/FaceTheFacts/web/pull/47) |              |             |

**Comment by FabianVolkers** [comment]
All commits on develop have now been squashed and replayed onto [develop-clean](https://github.com/FaceTheFacts/web/tree/develop-clean).

Final todos:

- [x] rebase all active branches onto the new branch. Shouldn't be hard, the only change should have been introduced by #43
- [x] cherry-pick 39/feature/search
- [x] cherry-pick 48/feature/profile-resdesign
- [x] link the new commits in the old PRs
- [x] switch out default develop branch with develop-clean 
- [x] mention co-authors in squashed commits

**Comment by FabianVolkers** [comment]
There are some final touch ups I want to perform, some super minor, some crediting Liam with his work. Unfortunately it would mean creating another new branch on which to replay all commits. This should be trivial, considering the commit history is now linear, but would interrupt work again so we'll have to postpone it.

All changes are already reflected in [47/wip/repo-clean](https://github.com/FaceTheFacts/web/tree/47/wip/repo-clean). We would only have to cherry-pick all commits after 28c98ed

**Comment by FabianVolkers** [comment]
Clean up complete :)
